### ISSUE TITLE
Use sf4j instead of log4j2

### ISSUE THREAD

**Issue by sundy-li** [brainlag/JavaNSQClient#15]
I'd like to sf4j-log4j to instead of log4j2, cause sf4j is a simple Logging Facade  and could be used  in various logging frameworks (e.g. java.util.logging, logback, log4j) .
  If you think that's needed, I will open a merge request to you.

**Comment by brainlag** [comment]
I don't think I want that, you can use the log4j2-sfl4j-adapter if you want to route the log messages through sfl4j. Unless I find a really good reason to switch to the sfl4j API I will use log4j2.
