### ISSUE TITLE
does 1.0.0.RC2 supports nsq v0.3.7?

### ISSUE THREAD

**Issue by kevinho** [brainlag/JavaNSQClient#17]
i  run testing testProduceOneMsgSnappy,
producer works, but consumer doesn't work, the callback won't get any message.

**Comment by brainlag** [comment]
Snappy seems to have problems with small messages. https://github.com/nsqio/nsq/issues/532
If you see the same problem with many bigger messages then it might be broken.

**Comment by kevinho** [comment]
My fault, i made a mistake.

The default broadcast-address of nsqd is OS hostname, when the consumer get this address like "ubuntu:4151", it can not connect to the nsqd if consumer is not in the same host.

But there is no exception or error output, is there any improvement?

**Comment by brainlag** [comment]
There is not only a error output missing, there is actually a bug. I will fix it later today.
