### ISSUE TITLE
Is it possible implement a RMI call style in NSQ client?

### ISSUE THREAD

**Issue by vincentruan** [brainlag/JavaNSQClient#19]
Hi, 
As the title said, I wanna use NSQ to implement a simple service bus, it is very easy ti find that the pub/sub and queue way have already implemented in NSQ, but how to get return object in a NSQProducer? Or do you have any kindly subjection?

Best regards.

**Comment by brainlag** [comment]
I'm not 100% sure what you mean, but if you think to implement Remote-Procedure-Call over NSQ then this is really not a good idea.

**Comment by vincentruan** [comment]
RMI means R(remote) M(method) I(invoke), see as below image, the second line is my question.

![vertical cross functional template-20160419](https://cloud.githubusercontent.com/assets/3647894/14625549/a602540e-0616-11e6-815b-ebba9610f3b2.png)

**Comment by brainlag** [comment]
Ok so we are talking about the same thing. Like I said before this is not a good idea to do with NSQ. NSQ does not support it, this library does not support it and I would not try to implement it on top of NSQ.

**Comment by vincentruan** [comment]
Got it, thank you.
