### ISSUE TITLE
How do I fix in Eclipse?

### ISSUE THREAD

**Issue by fjjiaboming** [brainlag/JavaNSQClient#20]
![image](https://cloud.githubusercontent.com/assets/951124/14737271/dd8a4398-08ad-11e6-98eb-ecf6405fceec.png)

**Comment by brainlag** [comment]
See https://github.com/trustin/os-maven-plugin/blob/master/README.md at the very end.

**Comment by fjjiaboming** [comment]
hi, Bro . 
README.md    does not mention any tcnative jar.

@brainlag

**Comment by fjjiaboming** [comment]
@brainlag  Thanks
