### ISSUE TITLE
Unexpected network errors will cause consuming stop

### ISSUE THREAD

**Issue by icanfly** [brainlag/JavaNSQClient#27]
Consumer never be triggered about network error. For example, unplug the network cable, disable computer networks. so connections in consumer never be closed and remove.

I think should add heartbeat interval expire for connection. If last heartbeat interval exceeded, close and reconnection.

I will post my code improvements soon.

**Comment by icanfly** [comment]
https://github.com/brainlag/JavaNSQClient/pull/28

**Comment by brainlag** [comment]
#28 was merged so this should be fixed.
