### ISSUE TITLE
Incorrect usage of Netty's ByteBuf class in JavaNSQClient library

### ISSUE THREAD

**Issue by kant111** [brainlag/JavaNSQClient#34]
The following error happens simply when reading messages for a while from NSQConsumer.

[nioEventLoopGroup-2-2] ERROR io.netty.util.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected. Enable advanced leak reporting to find out where the leak occurred. To enable advanced leak reporting, specify the JVM option '-Dio.netty.leakDetection.level=advanced' or call ResourceLeakDetector.setLevel() See http://netty.io/wiki/reference-counted-objects.html for more information.

**Comment by brainlag** [comment]
Should be fixed with 6947bff3edabb1b602f5017dc5ffbd2eb445906e
