### ISSUE TITLE
Nullpointer Exception while connecting consumer.

### ISSUE THREAD

**Issue by vikash-tiwari** [brainlag/JavaNSQClient#37]
`JsonNode jsonNode = mapper.readTree(new URL(addr + "/lookup?topic=" + topicEncoded));
                LogManager.getLogger(this).debug("Server connection information: {}", jsonNode);
                JsonNode producers = jsonNode.get("data").get("producers");`

jsonNode value is not having "data" key but rather "producers" is in the same level:
`{"channels":["test1"],"producers":[{"remote_address":"127.0.0.1:52354","hostname":"vikash.tiwari","broadcast_address":"vikash.tiwari","tcp_port":4150,"http_port":4151,"version":"1.0.0-compat"}]}`

Producer and Consumer connection code is same as in instructions.

**Comment by agustincastanio** [comment]
+1

**Comment by vikash-tiwari** [comment]
@brainlag: I have created a PR for the solution along with backward compatibility.
