### ISSUE TITLE
Consumer does not close netty connection after invoking shutdown() method

### ISSUE THREAD

**Issue by rukyzhc** [brainlag/JavaNSQClient#7]
I found that after I call the shutdown() method of the NSQConsumer, there is still one thread of the netty nioEventLoopGroup

**Comment by rukyzhc** [comment]
It seems that you should invoke group.shutdownGracefully() in each connection's close() method.

something like
```
    public void close() {
        LogManager.getLogger(this).info("Closing  connection: " + this);
        channel.disconnect();
        group.shutdownGracefully();
    }
```

**Comment by brainlag** [comment]
I will look into it later today.

**Comment by brainlag** [comment]
I looked into it and don't think it is a great idea to shut down the EventLoopGroup when a consumer is shutdown, because the  group is shared by all consumers. I don't think this is a problem at all since we don't leak EventLoopGroups.

**Comment by rukyzhc** [comment]
Well, I agree that the EventLoopGroup should not be closed here. But it should still be closed somewhere when I want to stop the program gracefully.

Perhaps I need an additional static method "shutdown" in the Connection.java and call it after cleanClose all connections.

**Comment by brainlag** [comment]
I think the long term goal is to give the user more control over the the EventLoopGroup.

**Comment by rukyzhc** [comment]
Agree your suggestion, and I just propose a way that I can close my program :)

**Comment by brainlag** [comment]
See #10.
